var familyPicEl = document.querySelector("#family-picture");
var thanksEl = document.querySelector("#thank-you-text");
var currentDay = document.querySelector("#current-day");
var openingEl = document.querySelector(".opening");
var resultsEl = document.querySelector(".results");
var buttonEl = document.querySelector('#btn');

var pics = [ "./images/pic1.JPG", "./images/pic2.JPG", , "./images/pic3.jpg", "./images/pic4.jpeg", "./images/pic5.jpg", "./images/pic6.jpg", "./images/pic7.jpg", "./images/pic8.jpg", "./images/pic9.JPG", "./images/pic10.JPG", "./images/pic11.JPG", "./images/pic12.JPG", "./images/pic13.JPG", "./images/pic14.JPG", "./images/pic15.JPG", "./images/pic16.JPG", "./images/pic17.JPG", "./images/pic18.JPG", "./images/pic19.JPG", "./images/pic20.JPG", "./images/pic21.JPG", "./images/pic22.JPG", "./images/pic23.JPG", "./images/pic24.JPG", "./images/pic25.JPG", "./images/pic26.JPG", "./images/pic27.JPG", "./images/pic28.JPG", "./images/pic29.JPG", "./images/pic30.JPG", "./images/pic31.JPG", "./images/pic32.JPG", "./images/pic33.JPG", "./images/pic34.JPG", "./images/pic35.JPG", "./images/pic36.JPG", "./images/pic37.JPG", "./images/pic38.JPG", "./images/pic39.JPG", "./images/pic40.JPG", "./images/pic41.JPG", "./images/pic42.JPG", "./images/pic43.JPG", "./images/pic44.JPG", "./images/pic45.JPG", "./images/pic46.JPG", "./images/pic47.JPG", "./images/pic48.JPG", "./images/pic49.JPG", "./images/pic50.JPG", "./images/pic51.JPG", "./images/pic52.JPG", "./images/pic53.JPG", "./images/pic54.JPG", "./images/pic55.JPG", "./images/pic56.JPG", "./images/pic57.JPG", "./images/pic58.JPG", "./images/pic59.JPG", "./images/pic60.JPG", "./images/pic61.JPG", "./images/pic62.JPG", "./images/pic63.JPG", "./images/pic64.JPG", "./images/pic65.JPG", "./images/pic66.JPG", "./images/pic67.JPG", "./images/pic68.JPG", "./images/pic69.JPG", "./images/pic70.JPG", "./images/pic71.JPG", "./images/pic72.JPG", "./images/pic73.JPG", "./images/pic74.JPG", "./images/pic75.JPG", "./images/pic76.JPG", "./images/pic77.JPG", "./images/pic78.JPG", "./images/pic79.JPG", "./images/pic80.JPG", "./images/pic81.JPG", "./images/pic82.JPG", "./images/pic83.JPG", "./images/pic84.JPG", "./images/pic85.JPG", "./images/pic86.JPG", "./images/pic87.JPG", "./images/pic88.JPG", "./images/pic89.JPG", "./images/pic90.JPG", "./images/pic91.JPG", "./images/pic92.JPG", "./images/pic93.JPG", "./images/pic94.JPG", "./images/pic95.JPG", "./images/pic96.JPG", "./images/pic97.JPG", "./images/pic98.JPG", "./images/pic99.JPG", "./images/pic100.JPG",
    "./images/pic101.JPG", "./images/pic102.JPG", "./images/pic103.JPG", "./images/pic104.JPG", "./images/pic105.JPG", "./images/pic106.JPG", "./images/pic107.JPG", "./images/pic108.JPG", "./images/pic109.JPG", "./images/pic110.JPG", "./images/pic111.JPG", "./images/pic112.JPG", "./images/pic113.JPG", "./images/pic114.JPG", "./images/pic115.JPG", "./images/pic116.JPG", "./images/pic117.JPG", "./images/pic118.JPG", "./images/pic119.JPG", "./images/pic120.JPG", "./images/pic121.JPG", "./images/pic122.JPG", "./images/pic123.JPG", "./images/pic124.JPG", "./images/pic125.JPG", "./images/pic126.JPG", "./images/pic127.JPG", "./images/pic128.JPG", "./images/pic129.JPG", "./images/pic130.JPG", "./images/pic131.JPG", "./images/pic132.JPG", "./images/pic133.JPG", "./images/pic134.JPG", "./images/pic135.JPG", "./images/pic136.JPG", "./images/pic137.JPG", "./images/pic138.JPG", "./images/pic139.JPG", "./images/pic140.JPG", "./images/pic141.JPG", "./images/pic142.JPG", "./images/pic143.JPG", "./images/pic144.JPG", "./images/pic145.JPG", "./images/pic146.JPG", "./images/pic147.JPG", "./images/pic148.JPG", "./images/pic149.JPG", "./images/pic150.JPG", "./images/pic151.JPG", "./images/pic152.JPG", "./images/pic153.JPG", "./images/pic154.JPG", "./images/pic155.JPG", "./images/pic156.JPG", "./images/pic157.JPG", "./images/pic158.JPG", "./images/pic159.JPG", "./images/pic160.JPG", "./images/pic161.JPG", "./images/pic162.JPG", "./images/pic163.JPG", "./images/pic164.JPG", "./images/pic165.JPG", "./images/pic166.JPG", "./images/pic167.JPG", "./images/pic168.JPG", "./images/pic169.JPG", "./images/pic170.JPG", "./images/pic171.JPG", "./images/pic172.JPG", "./images/pic173.JPG", "./images/pic174.JPG", "./images/pic175.JPG", "./images/pic176.JPG", "./images/pic177.JPG", "./images/pic178.JPG", "./images/pic179.JPG", "./images/pic180.JPG", "./images/pic181.JPG", "./images/pic182.JPG", "./images/pic183.JPG", "./images/pic184.JPG", "./images/pic185.JPG", "./images/pic186.JPG", "./images/pic187.JPG", "./images/pic188.JPG", "./images/pic189.JPG", "./images/pic190.JPG", "./images/pic191.JPG", "./images/pic192.JPG", "./images/pic193.JPG", "./images/pic194.JPG", "./images/pic195.JPG", "./images/pic196.JPG", "./images/pic197.JPG", "./images/pic198.JPG", "./images/pic199.JPG", "./images/pic200.JPG", 
    "./images/pic201.JPG", "./images/pic202.JPG", "./images/pic203.JPG", "./images/pic204.JPG", "./images/pic205.JPG", "./images/pic206.JPG", "./images/pic207.JPG", "./images/pic208.JPG", "./images/pic209.JPG", "./images/pic210.JPG", "./images/pic211.JPG", "./images/pic212.JPG", "./images/pic213.JPG", "./images/pic214.JPG", "./images/pic215.JPG", "./images/pic216.JPG", "./images/pic217.JPG", "./images/pic218.JPG", "./images/pic219.JPG", "./images/pic220.JPG", "./images/pic221.JPG", "./images/pic222.JPG", "./images/pic223.JPG", "./images/pic224.JPG", "./images/pic225.JPG", "./images/pic226.JPG", "./images/pic227.JPG", "./images/pic228.JPG", "./images/pic229.JPG", "./images/pic230.JPG", "./images/pic231.JPG", "./images/pic232.JPG", "./images/pic233.JPG", "./images/pic234.JPG", "./images/pic235.JPG", "./images/pic236.JPG", "./images/pic237.JPG", "./images/pic238.JPG", "./images/pic239.JPG", "./images/pic240.JPG", "./images/pic241.JPG", "./images/pic242.JPG", "./images/pic243.JPG", "./images/pic244.JPG", "./images/pic245.JPG", "./images/pic246.JPG", "./images/pic247.JPG", "./images/pic248.PNG", "./images/pic249.JPG", "./images/pic250.JPG", "./images/pic251.JPG", "./images/pic252.JPG", "./images/pic253.JPG", "./images/pic254.JPG", "./images/pic255.JPG", "./images/pic256.JPG", "./images/pic257.JPG", "./images/pic258.JPG", "./images/pic259.JPG", "./images/pic260.jpeg", "./images/pic261.JPG", "./images/pic262.JPG", "./images/pic263.JPG", "./images/pic264.JPG", "./images/pic265.JPG", "./images/pic266.JPG", "./images/pic267.JPG", "./images/pic268.JPG", "./images/pic269.JPG", "./images/pic270.JPG", "./images/pic271.JPG", "./images/pic272.JPG", "./images/pic273.JPG", "./images/pic274.JPG", "./images/pic275.JPG", "./images/pic276.JPG" ]

var quotes = [ "Thank you for always throwing the best parties. I love coming home and getting to see all of our friends and family - Vince", "Thank you for the best siblings I could ask for - Jess", "Thanks for letting Joe wear football pants to the zoo as a kid. That kid is funny! - Vince", "Thanks for Bailey.... I miss Bailey - Vince", "Thanks for all the orange chicken you've made me - Vince", "Thanks for all the rides to and from Fenwick. - Vince", "Thank you for taking care of the Sharonville Eagles. That place was awesome when we ran it - Vince", "Thanks for helping me get through skewl - Vince", "Thank you for talking to me on the phone every day - Jess", "Thank you for the best wedding ever - Jess", "Thank you for going shopping and always picking out the best clothes - Jess", "Thank you for entertaining Bailey all the time - Jess", "Thanks for helping me with all of my move ins and move outs!! - Nick", "Thank you for the pool it's great in the summer - Jess", "Thank you for keeping me sane - Jess", "Thank you for helping me with my house - Jess", "Thank you for always being there for me - Jess", "Thank you for waking up at 3 in the morning to check my blood sugars (and Joes!) - Jess", "Thank you for coming to all of my track meets. The best one was still when Beth fell over the hurdles - Jess", "Thank you for taking Branden and I to dinner we always love your and dad's company - Jess", "Thank you for pushing us all to do our best and be our best - Jess", "Thank you for all of the greatest trips. I love spending time away and with the entire family. - Jess", "Thank you for taking us snorkeling - Jess", "Thank you for the dinosaur egg oatmeal - Jess", "Thank you for the best holidays, Halloween our costumes were always great, Christmas has never been boring, Thanksgiving is always fun - Jess", "Thank you for curling my hair when we Irish danced - Jess", "Thank you for coming to all of my basketball games - Jess", "Thank you for coaching the softball team - Jess", "Thank you for the world's best gossip - Jess", "Thank you for always encouraging me - Jess", "Thank you for being my Broadway friend - Jess", "Thank you for always letting me have friends over. - Jess", "Thank you for going to the mother daughter sock hops - Jess", "Thank you for watching the Bachelor with me - Jess",
     "Thank you for sending me to girl scout camp - Jess", "Thank you for sending me to Catholic grade school and high school - Jess", "Thank you for all the Wendy's baked potatoes before practice! - Nick", "Thank you for letting me go to Teen Night at the sharonville rec center - Jess", "Thank you for taking Kelly and I to the Redskin games - Jess", "Thank you for taking us to Keeneland, love betting the horses - Joe", "Thank you for all the pictures you take of all of us 'Why is everything always like a vacation' - Jess", "Thank you for doing all of our laundry - Jess", "Thank you for cooking retarded spaghetti - Jess", "Thank you for getting your nails done with Kelly and I - Jess", "Thank you for the Golf Ranch - Jess", "Thank you for the cheesy potato recipe! - Jess", "Thank you for helping with homework even when I got frustrated - Jess", "Thank you for singing to us before bedtime - Jess", "Thank you for shoe shopping! - Jess", "Thank you for telling me when I am overreacting - Jess", "Love you lots, Mom!!! Thank you for everything you do for all of us! - Jess", "Thanks for making your calendar, we'd all be lost without it - Dad", "Thanks for running the financials and keeping us all afloat. - Dad", "Thanks for putting the family first and looking so good while doing it. - Dad", "Thanks for the incredible amount of support for all of us. - Dad", "Thanks for always giving your best, no matter how you are feeling. - Dad", "Thanks for always understanding and being patient - Dad", "Thanks for always making us laugh. - Dad", "Thanks for being the family doctor at home. - Dad", "Thanks for always putting our family first. - Dad", "Thanks for always having a positive attitude and making it easier for the rest of us. - Dad", "Thanks for always seeing the good in everything. - Dad", "Thanks for being the one person we all know we can count on. - Dad", "Thanks for being a great listener and advisor. - Dad", "Thanks for all the time that you set aside for the family. - Dad", "Thanks for always having a plan, even when we try to wing it. - Dad", "Thanks for always challenging us to be better and keep growing. - Dad", "Thanks for all the great memories and the ones to come. - Dad", "Thanks for the best vacations ever. - Dad", "Thanks for encouraging the family to find and follow their dreams. - Dad", 
     "Thanks for all the great meals. - Dad", "Thanks for taking care of the house, including building this one. - Dad", "Thanks for always having positive input when issues arise. - Dad", "Thanks for always being patient and encouraging that in us as well. - Dad", "Thanks for making us all feel so lucky to have you. - Dad", "Thanks for always being our number one fan. - Dad", "Thanks for making every day new and special. - Dad", "Thanks for always sharing in our happiness and success. - Dad", "Thanks for making us smile, no matter how bad the day was. - Dad", "Thanks for making times when we get together special and a blast. - Dad", "Thanks for our 5 little angels. - Dad", "Thanks for our amazing family. - Dad", "Thanks for loving ice cream and chocolate. - Dad", "Thanks for having the fashion sense to help those of us who don't. - Dad", "Thanks for always making our living space feel like a home. - Dad", "Thanks for saying 'yes'. - Dad", "Thanks for always having our back. - Dad", "Thanks for always wanting to have as much fun as possible. - Dad", "Thanks for getting us to places on time. - Dad", "Thanks for all the sunshine on rainy days. - Dad", "Thanks for all the sacrifices that you made to make us better. - Dad", "Thanks for believing in us. - Dad", "Thanks for all the love that you give. - Dad", "Thanks for trying new things. - Dad", "Thanks for being cool. - Dad", "Thanks for holding our hands when we need it most. - Dad", "Thanks for the great nights and weekends. - Dad", "Thanks for making everything better, just by being there. - Dad", "Thanks for always trying to make everyone else happy. - Dad", "Thanks for always being the calm in the middle of the storm. - Dad", "Thanks for loving your bourbon. - Dad", "Thanks for your gambling 'skills' and love for the track. - Dad", "Thanks for passing on your good looks to our children. - Dad", "Thanks for all the flowers. - Dad", "Thanks for loving sports. - Dad", "Thanks for making our family, our trips, our house and our parties the ones that everyone else wants to be part of. - Dad", "Thanks for always being a flow rider and not a wave maker. - Dad", "Thanks for your ideas and vision. - Dad", "Thanks for laughing at our jokes. - Dad", "Thank you for passing on your graceful athleticism to all of us! - Nick",
     "Thank you for giving me my 4 very best friends!! - Kelly", "Thank you for being my book partner - there's nothing better than going to Barnes and Noble to pick out new books, but the best is being able to discuss them with you! - Kelly", "You're only going to hear this once - thanks for my good looks (; everyone ALWAYS says I look just like you, well I guess I'm pretty darn lucky. - Kelly", "Thank you for always being down to get Larosas when I'm home. - Kelly", "Thank you for being my Dunkin buddy - anytime of the day, I know you'll go with me. - Kelly", "Thank you for always being a phone call away. - Kelly", "Thank you for believing in me even when I may not believe in myself. - Kelly", "Thank you for being my calm, even when I'm stressed to the max. - Kelly", "Thank you for supporting me and my dreams, no matter where in the world they take me! - Kelly", "Thank you for always being my shopping buddy at home. - Kelly", "Thank you for sharing your closet with me when I need something at home. - Kelly", "Thank you for all of the family vacations and the memories - we are one lucky family. - Kelly", "Thank you for getting your nails done with me! I love spending that time together. - Kelly", "Thank you for all the breakfasts in bed we had while growing up. - Kelly", "Thank you for making every trip home a special one!! Whether it's a weekend, a week, a holiday, being home is always a treat. - Kelly", "Thank you for binge watching Harlan Coban shows with me, they may not always be the greatest, but I enjoy sharing them with you! - Kelly", "Thanks for always being down for desserts when I'm home - I know you say I make you fat - but I do love a good dessert with you! - Kelly", "Thank you for our family - may seem obvious but we are one lucky family thanks to you, the glue that keeps us all together. - Kelly", "Thank you for helping me with my taxes and all other financial aspects of life. - Kelly", "Thank you for all the days you chaperoned a trip or worked at the school, it was always pretty cool to have the 'cool mom' at school. - Kelly", "Thank you for allowing us to be a part of endless sports and activities, I don't know how you got us everywhere we needed to be, but I'm grateful. - Kelly", 
     "Thank you for placing a priority on education and making sure we were all able to go where we wanted to and supporting us while there - not many people are that lucky. - Kelly", "Thank you for all the Disney World trips and memories. Greatest place on earth!! - Nick", "Thank you for allowing us and encouraging us to get out and see the world. - Kelly", "Thank you for Disney - you have no idea how special all those memories are - truly the happiest place on earth because of all that we have shared there. - Kelly", "Thank you for all of the shoes and clothes I seem to find while I am at home! - Kelly", "Thank you for helping me move numerous times in NYC and spending your anniversary with me like 4 years in a row moving me back in to school. - Kelly", "Thank you for your cheesy potatoes and chicken tetrazzini! - Kelly", "Thank you for always being a baking buddy and always making us a cake or pan cookie for our birthday. - Kelly", "Thank you for always making the holidays such a special time for our family. - Kelly", "Thank you for loving us unconditionally- no if's, ands, or buts - you are always there for us. - Kelly", "Thank you for always putting us first and teaching us what a family should be - I hope I can create one as special as ours some day! - Kelly", "Thank you for creating endless opportunities for all of us to be together, whether that be at home or somewhere else, you make an effort for all of us to be together when we can be! - Kelly", "Thank you for the endless flights you have been on to come and visit us - wherever that may be. - Kelly", "Thank you for all the laughs and smiles growing up - your positivity every single day. - Kelly", "Thank you for all the toys and games you gave us growing up! My many barbies, Polly pockets, dress ups and more - you always made sure we were happy. - Kelly", "Thank you for always being a listening ear - if I just need to bitch, you always let me get it out and I appreciate that. - Kelly", "Thank you for being the best mom there is - you are a strong ass lady and I hope someday I can be as awesome as you, I look up to you more than you know. - Kelly", "Thank you for all the bomb ass parties we have had - super bowl parties, holiday parties, bunco parties, birthday parties, and more - everyone wishes they were us!!(; - Kelly", 
     "Thank you for always allowing us to come home - even when home is a little tiny one bedroom apartment stuffed with way too many people. - Kelly", "Call me today! I miss you and I love you - Nick", "Thank you for the best vacations ever. When is the next one?! - Nick", "Thank you for being my hero - Vince", "Thank you for putting me in a position to chase my dreams! - Vince", "Thanks for believing in me, you and Dad are the reason for my confidence - Vince", "Thanks for telling me to change the world rather than shoot my ideas down! - Vince", "Thank you for always being the best team mom, and for not letting the best coach lose his shit - Nick", "Thanks for always being our biggest fans and the best cheerleader! Always felt different knowing you were at a game - Nick", "Thank you for mini muffins every Friday. Those slap. - Nick", "Thank you for a bag of donuts every Friday morning - Vince", "Thank you for putting up with all the worst girlfriends! Thank you I'm sorry I love you!!!!!!! - Nick", "Thank you for helping me poop before football practice when I was little! Can't play full of shit. - Nick", "Thank you for always being around school and so supportive. And also the coolest mom there - Nick", "Thank you for making us all such Jim beam fanatics!! And fun people everywhere we go - Nick", "Thanks for the best siblings and family in the world - Nick", "Thanks for showing us all the best relationship, marriage, parents, and everything else you and dad have shown us for so long - Nick", "Thanks for reminding dad of people's names everytime he forgets - Nick", "Thank you for reminding Nick to not drink too much water before he goes to sleep - Joseph", "Thank you for encouraging us to wear outrageous outfits. We are always the best dressed - Joe", "Thank you for not letting me change my major to business....Jesus that would've been a waste - Joe", "Thanks for forcing Joe to come to swim lessons so that we could all still learn to swim - Nick", "Thanks for the best summers of bowling and golfing! - Nick", "Thank you for driving me to all the away games when I was hurt for the season. It would have killed me to miss those games - Joe", "Thank you for the best cook! Miss your tetrazini all the time - Nick", "Thanks for always helping with school projects! Still not artistic or creative at all but I survived! - Nick", 
     "Thank you for taking me to Disney world, Mexico, Emerald Isle, Germany , everywhere! We have the most fun vacations!- Joe", "Thank you for surviving all the car rides to Disney and North Carolina! - Nick", "Thank you for volunteering at Christmas Village - Jess", "Thank you for always being down to do a cook out with Hammann kabobs!! - Kelly", "Thank you for all the care packages. At Columbia and still now, I always need them and love them! - Nick", "Thank you for doing our taxes - Jess"]

var today = moment().format("dddd MMMM Do, YYYY");
var date = moment().format("MMMM Do, YYYY");

var makeDay = function() {
    currentDay.append(today);
};

var picture = function() {
    if (date) {
        var img1 = document.createElement("img");
        img1.src = pics[Math.round((Math.random()*276))];
        familyPicEl.append(img1);
        var quote1 = document.createElement("p");
        quote1.innerHTML = quotes[Math.round((Math.random()*176))]
        thanksEl.append(quote1);
    }
}
var buildResults = function() {
    openingEl.classList.add("none");
    resultsEl.classList.remove("none");
};

buttonEl.addEventListener('click', function () {
    buildResults();
    picture();
});

makeDay();